export const editorGitSplitCoverageManifest: Record<string, string[]> = {
  'ui/src/editor/documentSession.ts': ['tests/unit/ui/editor/document-session.test.ts'],
  'ui/src/editor/documentWorkingCopy.ts': ['tests/unit/ui/contexts/content-tab-editing.test.ts'],
  'ui/src/editor/saveDocument.ts': ['tests/unit/ui/editor/save-document.test.ts'],
  'ui/src/editor/inlineEdit.ts': ['tests/unit/ui/editor/inline-edit.test.ts'],
  'ui/src/editor/unsavedGuards.ts': ['tests/unit/ui/editor/unsaved-guards.test.tsx'],
  'ui/src/editor/useUnsavedChangesGuard.tsx': ['tests/unit/ui/editor/unsaved-guard-integration.test.tsx'],
  'ui/src/editor/useDocumentConflictResolution.tsx': ['tests/unit/ui/editor/conflict-resolution-integration.test.tsx'],
  'ui/src/history/contracts.ts': ['tests/unit/ui/history/history-client.test.ts'],
  'ui/src/history/historyClient.ts': ['tests/unit/ui/history/history-client.test.ts'],
  'ui/src/contexts/editorUiTranslations.ts': ['tests/unit/ui/contexts/editor-ui-translations.test.ts'],
  'ui/src/contexts/splitViewTranslations.ts': ['tests/unit/ui/contexts/split-view-translations.test.ts'],
  'ui/src/components/Content/PlainMarkdownEditor.tsx': ['tests/unit/ui/components/plain-markdown-editor.test.tsx'],
  'ui/src/components/Content/InlineMarkdownEditor.tsx': ['tests/unit/ui/components/inline-markdown-editor.test.tsx'],
  'ui/src/components/Content/useInlineMarkdownEditing.ts': ['tests/unit/ui/components/use-inline-markdown-editing.test.tsx'],
  'ui/src/components/Content/DocumentSurface.tsx': ['tests/unit/ui/components/document-surface.test.tsx'],
  'ui/src/components/Content/SplitContent.tsx': ['tests/unit/ui/split-view/split-content.test.tsx'],
  'ui/src/components/Content/SplitDivider.tsx': ['tests/unit/ui/split-view/split-shell.test.tsx'],
  'ui/src/components/Content/SplitDocumentView.tsx': ['tests/unit/ui/split-view/split-shell.test.tsx'],
  'ui/src/components/Modal/UnsavedChangesModal.tsx': ['tests/unit/ui/editor/unsaved-guards.test.tsx'],
  'ui/src/components/Modal/DocumentConflictModal.tsx': ['tests/unit/ui/editor/conflict-modal.test.tsx'],
  'ui/src/split-view/paneSelectors.ts': ['tests/unit/ui/split-view/pane-selectors.test.ts'],
  'ui/src/split-view/paneState.ts': ['tests/unit/ui/split-view/pane-state.test.ts'],
  'ui/src/split-view/splitViewReducer.ts': ['tests/unit/ui/split-view/split-reducer.test.ts'],
  'electron/workspace/document-write.js': ['tests/unit/electron/document-write.test.ts'],
  'vscode/src/core/panelDocumentWrite.ts': ['tests/unit/vscode/panel-document-write.test.ts'],
};